collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  content_en:
    path: content/en
    name: Content En
    icon: content_cut
  content_nl:
    path: content/nl
    name: Content Nl
    icon: content_cut
  themes_hugobricks_i18n:
    path: themes/hugobricks/i18n
    name: Themes Hugobricks I18n
    icon: electric_rickshaw
  data:
    path: data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
paths:
  static: static
  uploads: static/uploads
timezone: Europe/Amsterdam
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: true
    superscript: true
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
